#!/usr/bin/env python3
"""
validate_checkpoints.py

Lightweight CI-style validation for the Release 4.0 (R12-CROWN) suite.

Behavior:
- Reads checkpoints from checkpoints.yaml
- Reads metrics from outputs/validation_report.csv (generated by run_all.py)
- Re-evaluates PASS/FAIL and exits non-zero on any failure.

This is intentionally conservative: it validates the published checkpoints, not every intermediate plot.
"""
from __future__ import annotations

import sys
from pathlib import Path
import pandas as pd
import yaml

def compare(value: float, comparator: str, threshold: float) -> bool:
    if comparator == "<":
        return value < threshold
    if comparator == "<=":
        return value <= threshold
    if comparator == ">":
        return value > threshold
    if comparator == ">=":
        return value >= threshold
    raise ValueError(f"Unsupported comparator: {comparator!r}")

def main() -> int:
    root = Path(__file__).resolve().parent
    chk_file = root / "checkpoints.yaml"
    report_file = root / "outputs" / "validation_report.csv"

    if not chk_file.exists():
        print(f"[FAIL] Missing checkpoints file: {chk_file}", file=sys.stderr)
        return 2
    if not report_file.exists():
        print(f"[FAIL] Missing validation report: {report_file}", file=sys.stderr)
        print("       Run: python run_all.py", file=sys.stderr)
        return 2

    with chk_file.open("r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    cps = cfg.get("checkpoints", [])
    if not cps:
        print("[FAIL] No checkpoints found in checkpoints.yaml", file=sys.stderr)
        return 2

    df = pd.read_csv(report_file)
    if "ID" not in df.columns or "Value" not in df.columns:
        print("[FAIL] validation_report.csv missing required columns (ID, Value).", file=sys.stderr)
        return 2

    failures = []
    for cp in cps:
        cid = cp["id"]
        comp = cp["comparator"]
        thr = float(cp["threshold"])
        rows = df[df["ID"] == cid]
        if rows.empty:
            failures.append((cid, "missing from validation_report.csv"))
            continue
        val = float(rows.iloc[0]["Value"])
        ok = compare(val, comp, thr)
        if not ok:
            failures.append((cid, f"value={val} fails {comp} {thr}"))

    if failures:
        print("[FAIL] Checkpoints failed:", file=sys.stderr)
        for cid,msg in failures:
            print(f"  - {cid}: {msg}", file=sys.stderr)
        return 1

    print("[PASS] All checkpoints satisfied.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
